Expand release management workflow for `dom0-config` to include `yum-qa` process
freedomofpress/securedrop-dev-docs pull request #116
Opened 2023-12-14 20:11 UTC by nathandyer

## Status

Ready for review 

## Description of Changes

This PR expands the RPM release management section, or at least the portion dedicated to `securedrop-workstation-dom0-config`, to match the `apt` counterpart above, and incorporate the `yum-test` and `yum-qa` repos.

* Resolves #113 

## Testing

- [ ] CI passes
- [ ] Visual inspection
- [ ] Described process aligns with real-world process

## Checklist (Optional)

- [x] Doc linting (`make docs-lint`) passed locally
- [ ] Doc link linting (`make docs-linkcheck`) passed
- [x] You have previewed (`make docs`) docs at http://localhost:8000

2024-01-23 21:12 UTC, zenmonkeykstop requested changes
Flagged some confusing/inaccurate bits. IMO more specific detail (CLI stuff etc) would be required, but that might be best generated during a release run.

2024-01-23 21:12 UTC, zenmonkeykstop commented on docs/workstation_release_management.rst
> +the pull request against ``securedrop-yum-qa``. Once the package is uploaded there,
There is no securedrop-yum-qa, I think. The preflight procedure as I understand it is the same as for the repos:
- create and sign prod RPM
- create a `release` branch on the `securedrop-yum-prod` repo and add the RPM there
- submit a PR for that branch - a webhook will deploy it to yum-qa.securedrop.org
- do preflight checks (as described below)
- when good, merge to `main`, which will deploy it to prod.

2024-10-30 20:02 UTC, eloquence commented
@nathandyer Worth reviving?

2025-04-16 20:28 UTC, nathandyer commented
Closing this PR as stale in favor of further QA automation instead

2025-04-16 20:28 UTC, closed without merging