WIP: Run CI using GitHub Actions
freedomofpress/securedrop-dev-docs pull request #51
Opened 2023-04-12 18:24 UTC by legoktm

## Status

Work in progress

## Description of Changes

* Description: Add CI using GitHub Actions

## Testing

* [ ] CI passes

2023-04-24 19:25 UTC, cfm requested changes
I like this a lot, @legoktm.  Even though this is the (or a) point of this effort, it's still _surprisingly_ nice to have the CI checks visible directly in GitHub: faster, more responsive, and lower-friction.

I've left a few stylistic nits inline.

2023-04-24 19:25 UTC, cfm commented on .github/workflows/ci.yml
> +          apt-get update && apt-get install -y --no-install-recommends make python3-pip
Nit (here and continuing below): Suggest expanding short flags in scripting for explicitness and readability:

```suggestion
          apt-get update && apt-get install --yes --no-install-recommends make python3-pip
```

2023-04-24 19:25 UTC, cfm commented on .github/workflows/ci.yml
> +          docker build --build-arg GIT_BRANCH=$(git rev-parse HEAD) -f deploy/Dockerfile .
```suggestion
          docker build --build-arg GIT_BRANCH=$(git rev-parse HEAD) --file deploy/Dockerfile .
```

2023-04-24 19:25 UTC, cfm commented on .github/workflows/linkcheck.yml
> +          apt-get update && apt-get install -y --no-install-recommends make python3-pip
```suggestion
          apt-get update && apt-get install --yes --no-install-recommends make python3-pip
```

2023-04-25 21:31 UTC, legoktm commented
Done, switched to long/full options (and will keep that in mind for future PRs :)).

2023-05-09 17:44 UTC, cfm approved these changes
Thanks, @legoktm!

2023-05-09 17:47 UTC, merged