WIP: Document packaging repositories
freedomofpress/securedrop-dev-docs pull request #81
Opened 2023-07-21 21:46 UTC by legoktm

## Status

Work in progress

## Description of Changes

Document how all the packaging repositories, how they work, etc.

Fixes #80.

* Related Issues

## Testing

*

## Release 

* 

## Checklist (Optional)

- [ ] Doc linting (`make docs-lint`) passed locally
- [ ] Doc link linting (`make docs-linkcheck`) passed
- [ ] You have previewed (`make docs`) docs at http://localhost:8000

2023-07-21 21:46 UTC, legoktm commented
This is a very rough WIP, needs more expansion, formatting, etc.

2025-03-19 20:44 UTC, legoktm commented
This is pretty old and I probably shouldn't have let this sit in a draft state for so long. But I've updated it for the new setup and think it's in a reasonable place to merge and iterate on.

2025-03-19 21:25 UTC, nathandyer requested changes
One possible mistake and one small flow-related suggestion, but otherwise this is looking great!

2025-03-19 21:25 UTC, nathandyer commented on docs/package_repos.rst
> +The Git repository contained the .deb and .rpm files and but only in some cases, the repository metadata too. When a new commit
Not quite sure what "and but only" means in this context. I assume the intent was that the "Git repository contained the .deb and .rpm files, and in some cases respository metadata too"?

2025-03-19 21:25 UTC, nathandyer commented on docs/package_repos.rst
> +are on ``*.securedrop.org``.
I think the note about domains should probably be higher in this document, in part for global context, but also so that the "There are three levels of package repositories..." line can then lead directly to the three subheadings where those are explained.

2025-03-20 14:28 UTC, legoktm commented on docs/package_repos.rst
> +The Git repository contained the .deb and .rpm files and but only in some cases, the repository metadata too. When a new commit
Yeah that's a better way to put it - thanks.

2025-03-20 18:22 UTC, nathandyer approved these changes
LGTM, thanks for fixing up those nits!

2025-03-20 18:25 UTC, merged